### ISSUE TITLE
Box plot component

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#119]
![image](https://user-images.githubusercontent.com/1484241/161850782-855509b7-4ea0-4db0-b2f0-0e44415f1ac5.png)

The BoxPlot could be for example in a table and I will try to generate a dataset.

Should we make the calculations in the Component so that we can directly provide the array ?

https://github.com/mljs/spectra-processing/blob/master/src/x/xBoxPlot.ts

We could also think about implementing small sparklines like 
https://www.npmjs.com/package/react-sparklines

**Comment by targos** [comment]
Is it meaningful to display a boxplot "on its own" ? Meaning without an axis and other boxplots to compare

**Comment by targos** [comment]
We should discuss again when we are closer to integrating this in a real application.

**Comment by lpatiny** [comment]
@targos, Lee has a problem to draw the axis because AutomaticHorizontalAxis is not exported in react-d3-utils.

Should he use independently the Axis from react-plot ?

https://deploy-preview-18--react-plot-docs.netlify.app/axes/axis

**Comment by targos** [comment]
Nothing from react-plot can be used independently.

**Comment by lpatiny** [comment]
Ok seems the best approach is then 'simply' to use react-plot directly. `react-plot` deals already with axes and annotations and has a userguide https://react-plot.zakodium.com/annotations/filledShapes that still need to be improved.

The only think we would need is to add a new kind of annotation.

I created an issue in react-plot https://github.com/zakodium-oss/react-plot/issues/406
