### ISSUE TITLE
Create buttons

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#135]
@Sebastien-Ahkrin please could you create new components:
- CloseButton
- ValidateButton

The CloseButton will be a refactor of the code from https://github.com/zakodium-oss/analysis-ui-components/blob/e3b93f0c2b22bbb3d8a27b057f2b2f4c2b662977/src/layout/Modal.tsx#L76-L86. Modal you then use this new component.

For the ValidateButton it should be based on the look of the green 'V' from the panels preferences

![image](https://user-images.githubusercontent.com/1484241/168225340-04b1667f-4e4e-46bb-80ba-7249f32d0903.png)

You could also move those new components and the existing Button component in a 'buttons' folder create the corresponding storybook.

**Comment by stropitek** [comment]
> ![image](https://user-images.githubusercontent.com/1484241/168225340-04b1667f-4e4e-46bb-80ba-7249f32d0903.png)

@lpatiny Are those unicode characters?
