### ISSUE TITLE
IV curves display

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#245]
Need to setup a way to display the curves of a A fairly standard galvanostatic cycling with potential limitation (GCPL) dataset with 6 cycles at a constant current rate. Here are some of the possible plots you can make with this data (though ec lab lets you make several other types as well):

<img width="693" alt="Screen Shot 2022-02-24 at 10 50 15 PM" src="https://user-images.githubusercontent.com/1484241/198823572-639b4af9-310c-43d8-8f6c-8c261357a21f.png">

<img width="770" alt="Screen Shot 2022-02-24 at 10 50 06 PM" src="https://user-images.githubusercontent.com/1484241/198823577-88fc63a5-3760-454b-b49f-cc49c7fdb83d.png">

<img width="678" alt="Screen Shot 2022-02-24 at 11 00 15 PM" src="https://user-images.githubusercontent.com/1484241/198823580-a8b9cefc-3c86-4005-90f0-9caefb71f11b.png">

![](https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41598-017-01236-y/MediaObjects/41598_2017_1236_Fig3_HTML.jpg)

![image](https://user-images.githubusercontent.com/1484241/195623180-b6b24fc8-38e3-4182-b6d3-c2b533635682.png)

**Comment by lpatiny** [comment]
Here is an example of a paper: https://pubs.acs.org/doi/abs/10.1021/acsenergylett.9b01441

And some images:

![image](https://user-images.githubusercontent.com/1484241/195635860-384cea54-f672-4bdb-ab2d-a94673a672e3.png)

![image](https://user-images.githubusercontent.com/1484241/195637207-a0efd33e-b72c-4318-9569-0b0db6d5d86f.png)

![image](https://user-images.githubusercontent.com/1484241/195637271-cdbe1147-2304-42a1-9dd7-ad3d8562b725.png)

![image](https://user-images.githubusercontent.com/1484241/195637341-7216c15f-e43b-491d-b200-004be7a2fe9d.png)

**Comment by lpatiny** [comment]
@santimirandarp Do we have an information about the cycle ?

Are we able to create those 3 schema ?

![image](https://user-images.githubusercontent.com/1484241/201168174-18c13547-14ce-4b10-9500-42da2bc0e005.png)

**Comment by targos** [comment]
@lpatiny You mentioned to me a Zenodo publication with many measurements. Can you share it here?

**Comment by lpatiny** [comment]
I only have those onces currently:

https://data.matr.io/1/projects/5c48dd2bc625d700019f3204
https://data.matr.io/1/projects/5d80e633f405260001c0b60a

But we found out there are not in biologic format.
