### ISSUE TITLE
Loaders should return log

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#291]
We have currently an issue tracking errors during data loading. This is the case in this project as well as in NMRium.

For each loader we should be able to return information about what they did.

I would suggest that the loader returns a structure like

```
{
  data: {} // the result of the parsing, in this case 'Measurements'
  logs: [{
     kind: 'error' | 'warning' | 'info' | 'debug',
     loader: 'NetCDF parser',
     message: 'The CDF is corrupted',
     relativePath: 'data/test/file.cdf',
     error: new Error('ab'),
  }]
}
```

@stropitek @targos What do you think ?

@jobo322 this is related to your current issue in nmr-load-save.

**Comment by targos** [comment]
We need something, but what you propose doesn't seem useful because we don't know which file has a problem.

**Comment by lpatiny** [comment]
I amended my issue to add the new property `relativePath`. This relativePath could be a link to a folder in case we try to parse a bruker file that contains soo many levels or just the path to a specific file like jcamp or netcdf.

WDYT ?

**Comment by stropitek** [comment]
Is the goal of this to show a helpful message to the user, or to be able to debug what is happening when files are loaded?

**Comment by lpatiny** [comment]
In the specific case of convert-biologic you should add in the loader a try / catch so that it does not crash and for each file add an entry in the log, either 'error' if failed or 'info' if success.

**Comment by santimirandarp** [comment]
I  could add it, but the loader already throws internally when the file is not supported. The error that I see in most parsers disappears if the crossHairAnnot is commented out.

**Comment by lpatiny** [comment]
It is very good that the convert throws and this should be not changed.

Those error could be catch during the loading. We could decide that for now the logs of all the loaders are just 'console.logged' but we need to think about a feedback to the user in the future.

I'm thinking that adding the property 'error' that contains the error that is catched could also help us to debug in the future what went wrong.

**Comment by lpatiny** [comment]
This issue can now be solved using fifo-logger and showing the errors is related to:
- https://github.com/zakodium-oss/react-science/issues/449
