### ISSUE TITLE
Build and publish galvanicium

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#294]
What would be the best strategy to have a build and release of 'galvanicium'.

Could we easily add a new entry point like [App.tsx](https://github.com/zakodium-oss/analysis-ui-components/blob/main/src/app/App.tsx) (add a folder galvanicium/App.tsx) and build / release this react application ?

We would then need to create the website based on this component in https://github.com/zakodium-oss/galvanicium

**Comment by stropitek** [comment]
It's being built in `src/pages/big-map`
