### ISSUE TITLE
Add shortcut in the tooltip

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#297]
Could we add the shortcut in the tooltip ? It should be platform dependent I guess.

![image](https://user-images.githubusercontent.com/1484241/198832543-d4d04b4c-2e0e-4431-b0c3-420c4f18a663.png)

@targos What is the best way to deal with the correct shortcut depending if it is a OsX or windows device ?

Is there anything in react-kbs that we could use or maybe there could be a utility in react-kbs that would deal with this issue.

I could not find in UTF-8 the actual symbols corresponding to the key `ctrl` and `cmd`. I found `alt` `⎇`

![image](https://user-images.githubusercontent.com/1484241/198832970-c1800812-b8d3-448a-990d-b7f2e0f09efd.png)

**Comment by targos** [comment]
I don't know. There's currently no relation between the button and the shortcut. They just call the same function.
