### ISSUE TITLE
Loading '.ium' from URL

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#315]
I'm currently writing the documentation of Galvanicum and wondering how we could reload a `.ium` file.

https://github.com/zakodium-oss/galvanicium#store--reload-experiments

It is clear about drag / drop but what about loading this file from a server ?

Do we agree that this is a specific case because this file replaces completely the state and therefore we should have a new property like 'iumURL' ?

Something like:

https://analysis-ui-components.pages.dev/#?iumURL=https%3A%2F%2Fzakodium-oss.github.io%2Fanalysis-dataset%2Fium%2Fiv.ium

**Comment by stropitek** [comment]
I think technically it does not have to be a different property since (AFAIK) it uses a `FileCollection` as for drag and drop.

Then when using remote data it's a more "authoritative" source so maybe we should be stricter than when doing drag and drop

**Comment by targos** [comment]
A different property compared to what?

**Comment by stropitek** [comment]
> A different property compared to what?

I was comparing it to `#?filelist=...` but this external resource is returning an `ium` file, not a file collection.

You can ignore my previous comment.

Definitely makes sense to have the `iumURL` property for this use case.

**Comment by targos** [comment]
We can implement support for loading `ium` files by URL but I don't see how that's relevant to the BIG-MAP project. We certainly don't want to document the format while it's in development so it seems useless to document how to serve it.
