### ISSUE TITLE
Implement message that can fade out

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#32]
Could display a help message for couple of seconds like:

![image](https://user-images.githubusercontent.com/1484241/133275891-dbab6e72-5544-4b0c-bc6d-fff7b7827cf2.png)

This message could also have different colors

<img width="357" alt="Screen Shot 2021-09-14 at 16 25 25" src="https://user-images.githubusercontent.com/1484241/133276023-59a28cdb-43d1-4f33-ade8-97e95beb1c07.png">

**Comment by targos** [comment]
This is similar to the toast notifications from `components`

**Comment by stropitek** [comment]
Blueprintjs has toast notifications

https://blueprintjs.com/docs/#core/components/toast
