### ISSUE TITLE
Rename repo / package

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#331]
@targos what would you think to rename this repo to react-analysis and to publish it scoped to the zakodium organization `@zakodium/react-analysis` since the name is already taken.

**Comment by targos** [comment]
What about `xxx-sdk` (where "xxx" could be "analysis" if we don't find a better word)

**Comment by lpatiny** [comment]
`measurements` was what we found to describe what could be spectra, chromatogram, iv or any X / Y data.

Or we could use `scientific` or `science` that will better cover our objectives.

**Comment by targos** [comment]
Idea we just had with Luc: `scientific-toolkit`, or `science-toolkit`.

**Comment by targos** [comment]
`react-science` will be the new name.

**Comment by targos** [comment]
To do before closing:
- [ ] rename project on Cloudflare pages
- [ ] release a first version on npm
- [ ] deprecate auic on npm
