### ISSUE TITLE
Create input component

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#346]
## Inspiration

https://ant.design/components/input/
https://ant.design/components/form/

I think the ant design fits well with this project, it's compact and rectangular (no rounded edges).
![image](https://user-images.githubusercontent.com/4118690/201345601-57517e10-b48a-41a8-94e9-3ed60d63f7c4.png)
![image](https://user-images.githubusercontent.com/4118690/201345650-a987eb31-a71a-4c02-a7d7-542aac8e9c06.png)
![image](https://user-images.githubusercontent.com/4118690/201346180-48bf4ca1-b1ac-46a4-827e-2a971c627f9c.png)
![image](https://user-images.githubusercontent.com/4118690/201347062-3745de83-1021-4e04-9c87-49e38ce99a50.png)
![image](https://user-images.githubusercontent.com/4118690/201348035-6f1fb07a-a344-4e95-89ac-b14d3cf7a068.png)
![image](https://user-images.githubusercontent.com/4118690/201348609-da2aea4e-0d30-4b1b-a63a-40ea68b4aa0c.png)

## Features (in order in which it should be implemented)
- Controlled component
- Forwards the native input props
- Placeholder
- 2 sizes
- With / without labels
- trailing / leading component (inline or not)
- validation feedback

## Features (to keep in mind for the future)
- Async validation

## API

```tsx
export interface CustomInputProps {
  leadingAddon?: ReactNode;
  leadingInlineAddon?: ReactNode;
  trailingAddon?: ReactNode;
  trailingInlineAddon?: ReactNode;
  loading?: boolean;
  help?: string; // Shown below the input
  error?: string; // Replaces help and in red
  valid?: boolean | string; // if true, changes the color of help, if string uses it instead of help
  inputClassName?: string;
}

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement>,
    CustomInputProps

function InputsWithLayout() {
  return (
    <Fields>
      // Field creates a context with the name as value and renders a <label htmlFor="field1" />
      <Field name="field1" label="Field 1">
        <Input /> // The id and name of the field is "field1" (through context)
      </Field>
      <Field label="Field 2">
        <Input />
      </Field>
    </Fields>
   );
}
```

## Implementation

We can steal a little bit from the existing implementation of the component in https://github.com/zakodium/components/blob/main/src/forms/basic/Input.tsx for how the elements in and around the input are layed out.

A major difference will be the label. It won't be possible to make it a prop of the input itself to achieve ant's layout of having labels in one column and inputs in another. That is why I added the `Fields` and `Field` components to the API.

**Comment by lpatiny** [comment]
Should we follow the renderers structure and have 2 components:
- TextInput
- NumberInput

I guess we would after get a wrapper with the renderer component on which you can click and it switch to an input component. Is this correct ?

**Comment by targos** [comment]
This issue has nothing to do with renderers. I don't understand the question.

**Comment by stropitek** [comment]
> Should we follow the renderers structure and have 2 components:
> 
> * TextInput
> * NumberInput

No the type of input is given by the `type` prop already.

> I guess we would after get a wrapper with the renderer component on which you can click and it switch to an input component. Is this correct ?

The issue already has a lot, and the focus is really just to render inputs, nothing more. If you mean to provide a way to do inline editing, I think it's better to use editable divs. But again it's off-topic.
