### ISSUE TITLE
Drop down and add item

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#350]
Does the current drop down menu allows to add new items ?

If not would it make sense to add this functionality or add a new component that allows to do it ?

![2022-11-12 10 14 17](https://user-images.githubusercontent.com/1484241/201480765-3a0c8168-2a88-4fce-bab9-d718d41073ea.gif)

@targos @stropitek WDYT ?

**Comment by targos** [comment]
TBH I don't think we need to make the workspaces so easy to create and delete. I would not add features for that in the drop down menu.
