### ISSUE TITLE
improve tabs component

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#403]
Can we render a custom tab header ( title ) ?
  currently in NMRium by default, we have ``` title``` which accepts a string or use can use the ```render``` property which is a function that 
    renders a custom tab title, and besides that, we have a delete button at the top left corner of the tab 
     
![image](https://user-images.githubusercontent.com/35760236/203557529-7882b0bd-63e8-4b3c-83b9-3d335b66f93e.png)
![image](https://user-images.githubusercontent.com/35760236/203556231-389c86c1-46d3-4f47-90b2-f8f1e15b037f.png)

**Comment by stropitek** [comment]
It's a very specific (and IMO peculiar) way of editing a list.

Not a strong case for adding a feature to a library which is meant tu support common cases that we can reuse a lot.
