### ISSUE TITLE
context drop-down menu 

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#443]
@targos 

I took a look at the context drop-down menu,  it seems you design it for general use so we do not know anything about the element that the context menu opens over it.

 let's assume I need to use it over a list or table I need to get the id or any other kind of data to use it once I press on the menu to do whatever I want.

maybe we could have a custom attributes `data-context = "" `

**Comment by targos** [comment]
I don't understand your problem. @stropitek ?

**Comment by hamed-musallam** [comment]
for example, we have a table displaying a list of spectra and I need to do an operation in one of the spectra so to do that I right-click on the row and open a context menu. How I can pass the id of the spectrum to the context menu?

**Comment by targos** [comment]
The way I would implement it is that each row of the table uses its own `DropdownMenu`. In that case you already have that information where you render the menu so that should be fine.

**Comment by hamed-musallam** [comment]
Do see it is better than having custom attributes per row and using `DropdownMenu` for the whole table?

**Comment by targos** [comment]
I don't really see any advantage of having a single menu for the whole table.

**Comment by hamed-musallam** [comment]
@targos 

Thanks, Michael, can you expose the `MenuOptions` ?

**Comment by hamed-musallam** [comment]
> I don't really see any advantage of having a single menu for the whole table.

But I think there is an advantage, we have a single drop-down context instead of having a drop-down menu in each table cell.

**Comment by targos** [comment]
That's a fact. But how is it an advantage?

**Comment by hamed-musallam** [comment]
I tested it per table header `<th>` , you can see the result 

![image](https://user-images.githubusercontent.com/35760236/213184889-24ccd647-a6f1-442b-885d-1fd2ce72eac1.png)

**Comment by hamed-musallam** [comment]
> I tested it per table header `<th>` , you can see the result
> 
> ![image](https://user-images.githubusercontent.com/35760236/213184889-24ccd647-a6f1-442b-885d-1fd2ce72eac1.png)
> 
> > That's a fact. But how is it an advantage?
> 
> just I mean we do not have to wrap the dropdown menu in each cell, nothing more

@targos 

this happen because i need to set     /* overflow: hidden; */ to ellipses the header

**Comment by hamed-musallam** [comment]
@targos 

I think the menu should be injected at the level of the table to avoid these style problem 

![image](https://user-images.githubusercontent.com/35760236/213188844-837139f3-5ec8-4775-95cd-7bfa974d85b6.png)

**Comment by targos** [comment]
No, we should be using a [Portal](https://github.com/zakodium-oss/react-science/blob/main/src/components/root-layout/Portal.tsx)

**Comment by hamed-musallam** [comment]
> @targos
> 
> I think the menu should be injected at the level of the table to avoid these style problem
> 
> ![image](https://user-images.githubusercontent.com/35760236/213188844-837139f3-5ec8-4775-95cd-7bfa974d85b6.png)

@targos  but we have the menu inside the `th`  as you can see??? is the wrong in how i use the component

**Comment by targos** [comment]
I don't know exactly, but there's definitely something wrong somewhere. If you could reproduce it in a story in this repo that would be perfect.

**Comment by hamed-musallam** [comment]
@targos 

i found the problem it is here https://github.com/zakodium-oss/react-science/blob/086f0b8621c250dd7b23e996924e474693586fec/src/components/dropdown-menu/DropdownMenu.tsx#L44-L46

**Comment by hamed-musallam** [comment]
@targos 

can you check the PR https://github.com/zakodium-oss/react-science/pull/444

**Comment by targos** [comment]
Fixed in v0.20.0. Thanks for the PR.
