### ISSUE TITLE
Stop click propagation on MenuItems

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#445]
@targos 

in NMRium, the spectra table column does two functionality 
1- order rows (Asc,Dec)
2- open the context menu

the click event on MenuItem trigger accidentally the order action, can we stop propagating the click event on the MenuItem ?

https://github.com/zakodium-oss/react-science/blob/0637f05eecf0c48c23a1ded7a78e7badeb00d35c/src/components/dropdown-menu/MenuItems.tsx#L129-L131

**Comment by targos** [comment]
yes
