### ISSUE TITLE
Vertical splitter freeze

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#450]
The `onResize` call-back should always return a real value because it does not make sense to have a value like "500.2px' and if we save this value without casting, the vertical splitter freeze.

**Comment by targos** [comment]
The `onResize` callback uses the same kind of value as the `initialSize` prop. I don't know why you think it doesn't make sense.
If there is a bug that makes it freeze, please show how to reproduce, or better: write a story.

**Comment by lpatiny** [comment]
I think @hamed-musallam you mean an integer value (rather than a real). Seems the resize is not working if the initialSize contains a decimal value

https://react-science.pages.dev/stories/?arg-s-initialSize=200.5px&story=components--splitpane--control

**Comment by targos** [comment]
From @lpatiny in https://github.com/zakodium-oss/react-science/issues/451

> https://react-science.pages.dev/stories/?arg-s-initialSize=200.5px&story=components--splitpane--control

> In the case of a split pane in 'px' unit, the callback often returns a decimal number (which is ok). However if the initialSize is '200.5px' (like in the example), the split pane would not work.

> Could you also take care that the story book works correctly and that if we change the value (initialSize) it is reflected directly in the story.
