### ISSUE TITLE
context menu position 

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#468]
if you take a look at the video and you focus on the top left corner you will see that the context menu is visible there for a pretty small time before it takes the right position on the row of the table

https://user-images.githubusercontent.com/35760236/229760836-5e507160-5ce4-4b76-803e-95843734552b.mp4

**Comment by targos** [comment]
This will probably be fixed by https://github.com/zakodium-oss/react-science/issues/469

**Comment by stropitek** [comment]
This is probably fixed since we moved to a completely new context menu component

@hamed-musallam feel free to reopen if not
