### ISSUE TITLE
Switch components from headlessui or radix to blueprint

### ISSUE THREAD

**Issue by targos** [zakodium-oss/react-science#469]
```[tasklist]
### Tasks
- [x] GradiantSelect
- [x] DropdownMenu
- [x] MenuItems
- [x] Dropdown stories
- [x] Remove headlessui dependencies
```

**Comment by targos** [comment]
@stropitek We should review this.

**Comment by stropitek** [comment]
Use radix-ui's `Collapsible` instead of headless-ui's `Disclosure`
Use radix-ui's `Select` instead of headless-ui's `Listbox`

**Comment by stropitek** [comment]
@wadjih-bencheikh18 can you prioritize this?

**Comment by targos** [comment]
The components were switched to radix-ui, not to blueprint, so this issue is not finished.

**Comment by targos** [comment]
Still not finished. I can see radix-ui used in:
- InfoPanel
- RadioGroup
- ButtonRadioItem
