### ISSUE TITLE
Can not superimpose 2 UV/VIS

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#482]
https://react-science.pages.dev/pages/demo#?filelist=https%3A%2F%2Fzakodium-oss.github.io%2Fanalysis-dataset%2Fuvvis.json

@wadjih-bencheikh18 Could you check why there is an issue when we try to superimpsoe 2 spectra ?

![2023-04-29 08 34 04](https://user-images.githubusercontent.com/1484241/235287794-9983e7fb-298f-458b-8df3-c674d2ff3ec3.gif)

**Comment by lpatiny** [comment]
There is still a bug if you unselect everything, you can not select anymore after. No spectrum will be displayed.

![2023-08-08 13 09 32](https://github.com/zakodium-oss/react-science/assets/1484241/8b1fdfac-214d-496b-8652-9a14db69986c)

**Comment by wadjih-bencheikh18** [comment]
> There is still a bug if you unselect everything

@lpatiny bug fixed
