### ISSUE TITLE
Clicking on accordion to open/close it is clunky

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/react-science#487]
When clicking on an accordion here, there is a small delay between click and the opening/closing of it. https://react-science.pages.dev/stories/?path=/story/components-accordion--fixed

The problem doesn't happen when clicking on delegated toggle buttons like https://react-science.pages.dev/stories/?path=/story/components-accordion--with-toggle

**Comment by targos** [comment]
Yeah, this is a known limitation. If you know a way to handle double click actions without triggering the click action twice, then we can fix this. Currently, we have this delay to wait for the second click. If it doesn't happen, then the click handler is called.

**Comment by targos** [comment]
The same happens for example in the Windows explorer.

**Comment by Xstoudi** [comment]
Thanks for the explanation.

Well, I'd say that having a double-click action that doesn't also trigger the single-click action at least once is an UX anti-pattern.

To be more precise, I mean in case you have to support double click, the single click action MUST be triggered before the double click action. Assuming this, if the consideration is triggering twice the click action : just listen `onClick` and differentiate the action to run using `MouseClickEvent.detail`.

To take Windows explorer as an example :
1. Click : select the folder
2. Double click : open the folder
But even when you double click on a folder, you can see that the folder style changed and was selected during the short time between the two clicks.

To be honest, I can't find any real life example of double click action that's not directly subsequent to single click action.

Have you a concrete example to not break if I PR something?

**Comment by tpoisseau** [comment]
I checked a bit this component with stories and code.
click => open / close item.
double click => open item, close all others (+ side effect of selecting a word in title)

If we keep this approach but without delay to differentiate simple vs double click, the only "weird" behavior will be :
On an opened item, double click will close it and reopen it (and close all others).
In this case, one possibility is to keep the item close (ie: double click on an opened item will close all items).

But in this context click may move element (it's another UX anti-pattern, click on an item should not move item away from cursor).

---

Other things to note :

May this component was done before `details` html element implemented in all browser, I suggest rework it to use this native implementation and avoid dynamic height on items, so closing an item don't make it move below the cursor.

**Comment by targos** [comment]
That said, we shouldn't worry too much about the design of the accordion component, because it's kind of a temporary solution for the panels.

**Comment by Xstoudi** [comment]
I agree with @tpoisseau about the `<details>` thing but it's for another time (modal and dropdown could also be concerned)

Map example is legit yet maps are so clunky and loading at every moment that it doesn't feel so weird.
Accordion are just supposed to open so it currently does feel weird :/ 

I'm not really sure that making every single accordions clunky just for a feature that minor and could be worked around is a good solution.  Would it be a problem for you if I either :
1. remove it completetly
2.  remove it and add a collapse all button on top of item
3. ctrl+click or alt+click to collapse all and expand the clicked on

When you say "temporary", how much temporary is it?` I need it in Pixelium so if a change is soon to be made it could be useful to make me aware of it.

**Comment by targos** [comment]
Let's remove the useDoubleClick hook and use <kbd>shift</kbd> + click to collapse all but the clicked on.
