### ISSUE TITLE
Typing storybook shortcuts in inputs triggers them

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#491]
For example, try typing `s` in an input: it opens / closes the storybook sidebar

Might be related to shadow dom? Because I don't remember having the same issues in other projects using storybook

**Comment by stropitek** [comment]
I made some research and I think I understand why storybook triggers shortcut actions when typing in inputs.

I read [this interesting article](https://pm.dartus.fr/blog/a-complete-guide-on-shadow-dom-and-event-propagation/) which reveals that:

> Most of the standard [UI events](https://w3c.github.io/uievents) bubble and are composed with a few exceptions. There are a few exceptions like mouseenter and mouseleave that aren't bubbling and composed.

The key here is that `composed` events leak to the shadow dom when they bubble up the dom tree.

If add an event listener on the storybook root like this:
```js
storybookRoot.addEventListener('keydown', (event) => { console.log(event.composedPath(), event.target)})
```

it gives this:
![CleanShot 2023-08-10 at 12 27 04](https://github.com/zakodium-oss/react-science/assets/4118690/3ef193a6-d8d4-4633-8e2f-364cf1cf7e16)

Therefore I suspect storybook to use the `target` property to know where the event originated from and if the event comes from within the shadow tree, the `target` element is the shadow host.

Will try to confirm that by searching in storybook's source code. Seems that could be fixable by using the result from `composedPath()`

**Comment by targos** [comment]
Is it possible to block event bubbling so it doesn't exit the shadow dom (not sure we want that though) ?

**Comment by stropitek** [comment]
> Is it possible to block event bubbling so it doesn't exit the shadow dom (not sure we want that though) ?

Could work but only if the listener of the event which we want to prevent is not the shadow host. But I don't know if it's possible to change the bubbling behaviour of a standard event.

**Comment by targos** [comment]
I wonder if the problem also affects storybook users who create custom elements (web components).

**Comment by stropitek** [comment]
https://github.com/storybookjs/storybook/pull/24179

**Comment by stropitek** [comment]
Fixed in storybook but also since we moved away from shadow dom.
