### ISSUE TITLE
Allow controlled side to make a scrollbar appear with overflow-x:auto

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/react-science#496]
Right now, I cannot move the split to the left, it's blocked by tabs:
![image](https://github.com/zakodium-oss/react-science/assets/2575182/9d83772b-4898-4242-9b3a-eb9a4fbd2830)

Adding `overflow-x: auto` to the root of the controlled side make it work as intended.
![image](https://github.com/zakodium-oss/react-science/assets/2575182/745955fc-b660-4115-9861-d16962aa38b1)

Is it okay if I PR to add `overflow-x: auto` on horizontal splitter's first child or is there a better way to achieve this?

**Comment by targos** [comment]
I'm pretty sure it can be fixed within the splitter by using the right CSS, but I can't help without a repro.

**Comment by Xstoudi** [comment]
It's on the `main` branch of Pixelium. https://github.com/zakodium-oss/pixelium

The SplitPane is here: https://github.com/zakodium-oss/pixelium/blob/main/src/components/Pixelium.tsx#L92

**Comment by targos** [comment]
I think the problem in Pixelium is that you are controlling the wrong side (double click closes the main view and only panels are visible).

**Comment by Xstoudi** [comment]
I fixed the controlled side thing on Pixelium, yet the second element of SplitPane cannot shrinks the opened tabs. Opening multiple images ultimately lead to the reduce of the sidebar, until the drama happen:
![image](https://github.com/zakodium-oss/react-science/assets/2575182/2fb6f803-4e86-4fa0-8012-79ebce545d57)

**Comment by Xstoudi** [comment]
Not really sure to understand your point.
The uncontrolled side already has a `minWidth: '300px'` ensuring it doesn't disapear in the void.
My goal here is to avoid that the tabs (controlled child) push the accordion (uncontrolled child). 

Said in an other way: the goal is to force the tabs generate a horizontal scrollbar if it cannot grow bigger the available space minus the width of the accordion (which minimum size must be ~300px).
