### ISSUE TITLE
Make Select a controlled component

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#498]
Did not notice this right away, but the component is not controlled. If `onSelect` is not passed to control some state outside of the component, it's not supposed have any effect when selecting an option.

`value` should be a mandatory prop, with the possibility to pass `undefined`

**Comment by Xstoudi** [comment]
On Radix side, this is not how it's handled.

If value is undefined, then the component is considered as uncontrolled and manage it's own state with no regard of `onSelect` value.

I'll push more stories to allow you to be more precise on what behavior is not as intended.

**Comment by stropitek** [comment]
Maybe I don't see the whole picture but IMO it can simplify the code in some cases but in general there are some downsides:
- It can lead to bugs where you think you have a controlled component but you forgot to pass the value and you end up with duplicated state.
- It becomes more code and work to make all components work in a coherent way (including components which don't use radix-ui)

I'm not completely opposed to it, but I haven't used uncontrolled components in a very long time and maybe I'm missing the upsides.



I would be in favour of fully controlled components just because it's an easier mental model if all of our components behave th
