### ISSUE TITLE
Ability to nest `Toolbar.Item` as an opening button for a `DropdownMenu`

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/react-science#515]
This example:

```tsx
    <DropdownMenu
      trigger="click"
      onSelect={selectOption}
      options={filterOptions}
    >
      <Toolbar.Item title="Filters">
        <FaFilter />
      </Toolbar.Item>
    </DropdownMenu>
```

leads to having two `button` tag nested, which trigger the following warning:
```
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
```

**Comment by targos** [comment]
Do you have a suggestion to fix it?

**Comment by targos** [comment]
Conceptually, you want the dropdown's trigger to be your toolbar item. I think we need to change the API to accept that. In other words, an option to render your own trigger button.

**Comment by stropitek** [comment]
@targos duplicate of https://github.com/zakodium-oss/react-science/issues/612?

**Comment by targos** [comment]
Seems like it.
