### ISSUE TITLE
New component: PanelHeader

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#519]
A PanelHeader could be used in the panel as a fixed header. It has 3 props:

- children
- count - if defined we put the number in square bracked on the right
- onClickSettings - if defined we add the gear on the right

It should replace in NMRium all the header of panels:

![image](https://github.com/zakodium-oss/react-science/assets/1484241/08ad7fb6-1bd0-4cef-8e10-3f3b2fc1d213)

It should also be used in Pixelium

**Comment by wadjih-bencheikh18** [comment]
In NMRium the setting button has tooltip on hover
Do I have to add it in this component?

**Comment by wadjih-bencheikh18** [comment]
We can add showSettingButton prop so PanelHeader can be more customizable

**Comment by stropitek** [comment]
> Do I have to add it in this component?

No, because the tooltip component does not exist yet (#522)
