### ISSUE TITLE
Extend the input component to have a 'search' component

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#547]
When there is a value the 'x' allows to clear the value.

There is a placeholder
There is a defualt 'magnifier' in front.

![2023-08-24 12 21 25](https://github.com/zakodium-oss/react-science/assets/1484241/d0bc01ab-b4ee-4a77-aa07-6fca64f2972d)

Once done this should be:
- implemented in the InfoPanel
<img width="531" alt="image" src="https://github.com/zakodium-oss/react-science/assets/1484241/b00fffc2-f830-414d-b8e6-c5a9fabf35b0">
- In NMRium database search
<img width="1058" alt="image" src="https://github.com/zakodium-oss/react-science/assets/1484241/f0a38491-0f28-4098-9b1a-7013f42b5355">

**Comment by stropitek** [comment]
Placeholder and "inline leading addon" (for the search icon) are already implemented.

To implement: add `onClear` prop which takes a callback and adds a clear button which calls the callback if the prop is defined.

IMO we can make the clear button more subtle (no background color) than what we have in nmrium.

**Comment by stropitek** [comment]
Passing `type="search"` when used in blueprintjs's `InputGroup` will format the input slightly differently and use the native "clear" feature. It's not supported in firefox (currently behind a flag with [an issue open](https://bugzilla.mozilla.org/show_bug.cgi?id=1654288) to have it the default).

https://blueprintjs.com/docs/#core/components/input-group.search-input

I think we can work with that.

Would be good though to have a story which shows the component in action, and shows what happens with `onValueChange` / `onChange` when the input is cleared.
