### ISSUE TITLE
Rewrite Modal components using blueprintjs's Dialog

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#550]
![image](https://github.com/zakodium-oss/react-science/assets/1484241/a9faa71d-c697-45ae-8625-a06076bca522)

There are multiple issues with the ConfirmModal, including how colors are defined and the component's API.

We have to work on buttons before handling this.

We would like this before merging: https://github.com/cheminfo/nmrium/pull/2618

**Comment by stropitek** [comment]
- Rewrite Modals which are not ConfirmModal with blueprintjs's Dialog
- Rename `ConfirmModal` to `ConfirmDialog`. It should use blueprintjs's Dialog. I think all of `Dialog`'s props can be forwarded by this component.

@wadjih-bencheikh18 If you notice any feature which were possible before but are lost when switching to blueprintjs, please write it down in the PR and we'll see case by case what we should do.
