### ISSUE TITLE
Info panel and smart ordering

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#563]
Searching in the info panel is a very helpful feature. However, the number of results can be overwhelming, and there is no option to sort them by relevance.

![2023-10-06 08 47 51](https://github.com/zakodium-oss/react-science/assets/1484241/f0d15c54-6e97-4404-9530-548ad2bf27b3)

We need to sort the result in the following prioriyn (everything is case insensitive !):

1. parameter name has an exact match
2. parameter name starts with
3. parameter name contains
4. value contains

**Comment by wadjih-bencheikh18** [comment]
@lpatiny Do we only search parameters or even values? 
in the current version we search matches in the two
