### ISSUE TITLE
Replace Tabs component

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#573]
Replace usage with blueprintjs
https://blueprintjs.com/docs/#core/components/tabs

I think in this case we can remove the stories.

![CleanShot 2023-10-18 at 11 55 04](https://github.com/zakodium-oss/react-science/assets/4118690/34cca617-1933-498c-889b-860f37442fc1)

to become

![CleanShot 2023-10-18 at 12 01 08](https://github.com/zakodium-oss/react-science/assets/4118690/705f9c68-1ec8-4111-86b7-95437c17d50f)

Since there is built-in support for "tags", we can use that to show the number of spectra loaded for each type.

**Comment by stropitek** [comment]
To check:

- Does it look better than the current implementation in the context of an application? => can be tested in the demo app.
- Is it widely used in NMRium? => can we make breaking changes to the API?

**Comment by targos** [comment]
There's only one use of the `Tabs` component from here in NMRium. All the others still use the old internal implementation.

**Comment by stropitek** [comment]
> There's only one use of the `Tabs` component from here in NMRium. All the others still use the old internal implementation.

👍🏻 we are free to just use the blueprintjs implementation then if it matches our needs
