### ISSUE TITLE
@wadjih-bencheikh18 can you create another PR which only fixes #521 ?

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#574]
@wadjih-bencheikh18 can you create another PR which only fixes #521 ?

I will close this PR since no longer relevant with the move to blueprintjs

_Originally posted by @stropitek in https://github.com/zakodium-oss/react-science/issues/548#issuecomment-1768437179_

**Comment by targos** [comment]
I don't see a new PR. What fixed this?

**Comment by wadjih-bencheikh18** [comment]
> I don't see a new PR. What fixed this?

It's fixed by #566
