### ISSUE TITLE
Toolbar items collapse

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium-oss/react-science#575]
![image](https://github.com/zakodium-oss/react-science/assets/56769876/6cdc9397-202f-4893-b256-517869e84b09)

**Comment by stropitek** [comment]
Can you point out the problem?

Do you have a working branch pushed in nmrium with the changes that lead to this?

**Comment by wadjih-bencheikh18** [comment]
I think the problem is not in `react-science`, It's just there was a breaking change in the toolbar component
I'm fixing it in `Nmruim`

**Comment by wadjih-bencheikh18** [comment]
> Yes, it's always good to look at the [changelog](https://github.com/zakodium-oss/react-science/blob/main/CHANGELOG.md) when updating a library

Yes, Thank you
We can close this issue then
