### ISSUE TITLE
Toolbar icons do not align correctly

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#590]
The icons take now the full width:

https://react-science.pages.dev/stories/?path=/story/components-toolbar--horizontal-toolbar

![image](https://github.com/zakodium-oss/react-science/assets/1484241/91436e9d-0fa4-4de9-89ab-e94d733b45f1)

And vertical icons appear on 2 columns

![image](https://github.com/zakodium-oss/react-science/assets/1484241/ba308113-6f90-4dda-83b5-94876b211ea2)

https://react-science.pages.dev/stories/?path=/story/components-toolbar--vertical-toolbar

**Comment by stropitek** [comment]
@wadjih-bencheikh18 can you look into this in priority?

**Comment by hamed-musallam** [comment]
The issue, as I can see from the Button component, is that it uses flex, which forces the buttons to expand equally in the area.

![image](https://github.com/zakodium-oss/react-science/assets/35760236/1c02af98-6c82-494a-af79-2163d4306360)


https://github.com/zakodium-oss/react-science/blob/main/src/components/button/Button.tsx#L26C6-L26C13

**Comment by hamed-musallam** [comment]
Could we also have the option to set the background and icon color for both cases (active and deactivate), 
the same is true for the tooltip?

**Comment by stropitek** [comment]
> Could we also have the option to set the background and icon color for both cases (active and deactivate),
> the same is true for the tooltip?

This might be possible with custom styles (would have to check) but I'm not sure we want this. Limiting customisation is key to having consistent user interfaces.

Using the `intent` prop is not enough? See https://react-science.pages.dev/stories/?path=/story/components-toolbar--control&args=intent:primary. What is the use case?
