### ISSUE TITLE
Toolbar with different intents

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#591]
I think it is enough but the issue with the `intent` it is been applied to the whole toolbar

_Originally posted by @hamed-musallam in https://github.com/zakodium-oss/react-science/issues/590#issuecomment-1846846736_

**Comment by stropitek** [comment]
Let's figure out if need each item in the toolbar to have a customisable `intent` or if we should create multiple toolbar for this purpose.

@hamed-musallam can you provide more info for your use case? Maybe a screenshot of how custom toolbar items are used in NMRium if that is already the case?

**Comment by wadjih-bencheikh18** [comment]
We can add `intent` prop to the `toolbarItem`
