### ISSUE TITLE
modal delete button position issue

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#593]
It appears to be incorrect since you are applying the style to the button inside a span, which should not be the case. This will cause issues, especially with test tools like Playwright, which waits for the element to be visible, enabled, and stable.

https://github.com/zakodium-oss/react-science/blob/fa300f8046149a9a4bdf78a227a82c8ee9f80ad4/src/components/modal/Modal.tsx#L118

https://github.com/zakodium-oss/react-science/blob/fa300f8046149a9a4bdf78a227a82c8ee9f80ad4/src/components/button/Button.tsx#L25-L29

**Comment by hamed-musallam** [comment]
Could we add a custom role or class to make it easy to access the delete button in the modal header?

**Comment by hamed-musallam** [comment]
@stropitek 

WDT ? Can we address and resolve it for the upcoming release, which will include fixes for this issue as well as those already resolved in https://github.com/zakodium-oss/react-science/pull/592

**Comment by hamed-musallam** [comment]
Alternatively, I could trigger the button press even if the button is not fully ready from the Playwright perspective, this is something i need to check if you see that this change we can not do right now

**Comment by stropitek** [comment]
Why is having a `span` wrapping an issue in general / with playwright?

There is a `renderTarget` prop in blueprintjs's Tooltip component which may help getting rid of the unnecessary span.

**Comment by stropitek** [comment]
> There is a `renderTarget` prop in blueprintjs's Tooltip component which may help getting rid of the unnecessary span.

@hamed-musallam Can you try this and create a PR?

https://blueprintjs.com/docs/#core/components/tooltip
