### ISSUE TITLE
Bad use of Blueprint's API

### ISSUE THREAD

**Issue by targos** [zakodium-oss/react-science#604]
From this repo in development:
![image](https://github.com/zakodium-oss/react-science/assets/2352663/029a4f4b-fee7-44e4-98ff-fbfdc356c044)

From nmrium, there's also another warning:
![CleanShot 2023-12-13 at 17 02 56](https://github.com/zakodium-oss/react-science/assets/2352663/df5530a8-e9e1-443c-bd81-7bf22de57bc3)

**Comment by stropitek** [comment]
Fixed by #605
