### ISSUE TITLE
Select does not close on escape key

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#632]
This is especially confusing when used in modals because then the modal closes.

In the examples of the documentation of bluprintjs, `Esc` closes the select list.

https://blueprintjs.com/docs/#select/select-component

**Comment by wadjih-bencheikh18** [comment]
It's only working for filtrable `Select` in https://blueprintjs.com/docs/#select/select-component I think they have a bug 
I'm using Popover autofocus with no portal which is working

**Comment by stropitek** [comment]
https://github.com/palantir/blueprint/issues/4243
