### ISSUE TITLE
Clicking outside to close the Color Picker is closing the modal 

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#638]
https://react-science.pages.dev/stories/?path=/story/components-color-pickers--color-picker-dropdown-story

https://github.com/zakodium-oss/react-science/assets/35760236/444a83c8-5491-4e92-8920-0c56896ffebf

**Comment by hamed-musallam** [comment]
After migrating to react-science version 0.33 and replacing the old Modal component with the Dialog component from Blueprint.js, the color picker is now appearing behind the Dialog

![image](https://github.com/zakodium-oss/react-science/assets/35760236/41f8c80d-ca93-4d16-88f7-57f86fe594b5)

**Comment by wadjih-bencheikh18** [comment]
@hamed-musallam @stropitek 
This happens because of `react-science` [Portal](https://github.com/zakodium-oss/react-science/blob/main/src/components/root-layout/Portal.tsx ) blueprint js portal are diffrent

So we need to refactor any `react-science` component that uses it.

**Comment by hamed-musallam** [comment]
I believe the color picker should use the Portal from Blueprintjs. As I can see, we have fully replaced the Modal with Dialog.
