### ISSUE TITLE
Measurement information panel improvements

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#640]
## More compact design ?

We have around 1000 parameters in NMR spectra and the rows could be more compact

![image](https://github.com/zakodium-oss/react-science/assets/1484241/6d65e37f-40b6-4b70-afe1-bc33844ef639)

## Search bar could be fixed

When we scroll we should keep the search bar fixed.

## Case insensitive is still a 'good' match

Currently if the table contain 'P1' and we search for 'p1' nothing if found. It should be case insensitive by default, also for ordering the results.

## Better visual separation of the different sections ?

In this example it is not clear when we switch of sections

## Counter with total number of rows (all sections) and selected number of rows.

Next to the search box we could have `[ 12/45 ]`

![image](https://github.com/zakodium-oss/react-science/assets/1484241/9fcaea17-8638-46d5-9a21-daf49dbda306)

## Table could take always full width

It does not look nice currently when you have many section and one take 100% width while the other one is much smaller.

![image](https://github.com/zakodium-oss/react-science/assets/1484241/99de1b4c-f55a-437b-a766-8017459373c4)

## Parameter should be sorted

The first columns containing the parameter label should be sorted by default (case insensitive sort).

![image](https://github.com/zakodium-oss/react-science/assets/1484241/42ee3c83-7f74-4fe2-8f04-f0dbed566354)

**Comment by stropitek** [comment]
> We have around 1000 parameters in NMR spectra and the rows could be more compact

The table component has a `compact` prop and it's not used in the info panel.
