### ISSUE TITLE
Add "count" (badge) to toolbar item

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#649]
It adds a small colored "pill" on the corner of the button with the count displayed.

We expect an integer to be passed and I think you can adapt the font size based on if there is 1, 2, or more digits in the number.

Example in NMRium:
![CleanShot 2024-02-09 at 15 42 54](https://github.com/zakodium-oss/react-science/assets/4118690/fbe9e41d-cfe8-4f15-9918-ca8feab66f37)

API suggestion:

```jsx
// text color is always white
<Toolbar.Item count={3} countBackgroundColor="red" />
```

**Comment by wadjih-bencheikh18** [comment]
I like this style, WDYT?

![image](https://github.com/zakodium-oss/react-science/assets/56769876/3c46fc34-1ef2-4bee-9372-e506d0280165)
And on hover
![image](https://github.com/zakodium-oss/react-science/assets/56769876/4a139cda-0a3b-4253-adab-f7add7734f3c)

I used Tag component https://blueprintjs.com/docs/#core/components/tag

**Comment by stropitek** [comment]
SGTM, see PR comments
