### ISSUE TITLE
Remove ButtonGroup component

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#657]
Replace story with a simple blueprintjs `ButtonGroup` example

**Comment by wadjih-bencheikh18** [comment]
Also we can do the same for `RadioGroup` component
https://react-science.pages.dev/stories/?path=/story/forms-radio--basic

The only problem is that `type="button"` is not available in blueprintjs. Is it interesting to have it?

**Comment by stropitek** [comment]
Creating another issue for `RadioGroup`
