### ISSUE TITLE
Reduce size of toolbar in the panels

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#679]
The icons in the header toolbar of panel should be slightly smaller that the one in the normal toolbar

![image](https://github.com/zakodium-oss/react-science/assets/1484241/1f2c8ed3-70ee-4bb5-8d37-4ed814e930c8)

**Comment by wadjih-bencheikh18** [comment]
https://github.com/zakodium-oss/react-science/pull/693

Do we close this issue?
