### ISSUE TITLE
Closing a dialog opens trigger tooltip

### ISSUE THREAD

**Issue by targos** [zakodium-oss/react-science#691]
Reproduce:
- Go to https://react-science.pages.dev/pages/demo
- Click on the about button (top-left)
- Press escape
- "About Logo" tooltip appears.

I think it's a case of https://blueprintjs.com/docs/#core/components/tooltip.combining-with-popover and we should decide to either set `shouldReturnFocusOnClose={false}` on the relevant dialogs, or `openOnTargetFocus={false}` on the `Toolbar.Item`.

/cc @stropitek

**Comment by stropitek** [comment]
setting `shouldReturnFocusOnClose={false}` is a better option (for UX, probably not for DX because cannot enforce it on every dialog) IMO

**Comment by targos** [comment]
This affects a bunch of dialogs on NMRium that are opened from a toolbar button.
