### ISSUE TITLE
[Info panel]: tables width 

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#702]
The info tables should match the width of the container

![image](https://github.com/zakodium-oss/react-science/assets/35760236/cb4c21cd-57e7-4c9c-9ae4-3175964dd59b)

**Comment by stropitek** [comment]
Probably fixed on HEAD

See: https://react-science.pages.dev/stories/?path=/story/components-infopanel--basic

I made a release, feel free to reopen in case you still have the issue with v2.0.0
