### ISSUE TITLE
Review Toolbar.Item and Toolbar.PopoverItem

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#704]
We should check which props we want to expose for each of those 2 components.

Right now we are exposing too many props and we should have an intermediate private component which exposes those.

Example: `isPopover` should not be exposed.

**Comment by hamed-musallam** [comment]
We shouldn't expose `isPopover`, and `popoverInteractionKind` is unnecessary for `Toolbar.Item`. It should be moved to the `Toolbar.PopoverItem` level.

**Comment by stropitek** [comment]
> `popoverInteractionKind` is unnecessary for `Toolbar.Item`

it is on the toolbar and that is fine IMO. I don't think a toolbar should mix different interaction kind together. It should be documented that it only affects the popover items.
