### ISSUE TITLE
InfoPanel first column width too small

### ISSUE THREAD

**Issue by moonayyur** [zakodium-oss/react-science#706]
Since the first column of `InfoPanel` only takes 30% of the width in the new design :
```
'td:first-child': {
  width: '30%',
},
```
It's not responsive with bigger texts

![image](https://github.com/zakodium-oss/react-science/assets/74436107/3fc5a358-1c8f-454c-b56a-5beb93e3a167)

see : https://github.com/zakodium-oss/pixelium/pull/93

**Comment by stropitek** [comment]
I'm assigning this to Wadjih since he worked on this in the first place
