### ISSUE TITLE
Do not scroll behind the search box in info panel

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#710]
In the info panel I would prefer that the table does not scroll behind the search box and that the search box position / size is fixed like in:

![2024-04-05 15 09 43](https://github.com/zakodium-oss/react-science/assets/1484241/e6bf6d72-1c68-4854-b6a4-51ace6bb6ead)

**Comment by wadjih-bencheikh18** [comment]
which option do you prefer
1
![image](https://github.com/zakodium-oss/react-science/assets/56769876/63977fdc-e767-442c-96a7-53f7396d3a82)

2
![image](https://github.com/zakodium-oss/react-science/assets/56769876/50e701ae-35cb-459d-b4c2-599d60614a37)

**Comment by lpatiny** [comment]
I prefer you repeat the headers (so indeed 2)
