### ISSUE TITLE
Create NMR file browser react-component

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-science#748]
@wadjih-bencheikh18 You can develop this new react component in this project but it will likely migrate somewhere else in the future. At least using storybook we could test it easily and make comments.

We need a component that allows to browse NMR file. There is 2 levels, one is the sample (the grey zone) and all the corresponding analysis (the white zone). There is a lot of buttons but practically there are only 2 possible callbacks:
- setSpectra
- appendSpectra

[html.zip](https://github.com/user-attachments/files/16333587/html.zip)

<img width="482" alt="image" src="https://github.com/user-attachments/assets/9f157f74-e6d5-420f-b46d-61b68df5311b">

- Please use react component for 1D, 2D, FT, FID as it will likely be customized in the future.
- By default only the 'grey' lines should be displayed and are expandable.
- We need a nice way to display relative dates but you should find a library that does it probably (and not use my little function)
- There should be a nice 'query' box with a throttling of 200ms I think.
- The layout should be compact as it will replace in some cases the right column in https://www.nmrium.org/nmrium#%3Ftoc%3Dhttps%3A%2F%2Fcheminfo.github.io%2Fnmr-dataset-demo%2Fsamples.json

<img width="275" alt="image" src="https://github.com/user-attachments/assets/e79c85df-e7d7-49bd-ab50-6393cfdff966">

**Comment by wadjih-bencheikh18** [comment]
We can close this issue
