### ISSUE TITLE
Remove app-specific components from library

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#786]
Either change the structure of this repository to be a mono-repo, or separate the demo app in a separate project.

**Comment by stropitek** [comment]
- Remove app-specific public exports
- Move any dependency not used anymore by public exports in `devDependencies`
- Export public library components directly in `'react-science'` instead of `'react-science/ui'`

**Comment by targos** [comment]
> Export public library components directly in `'react-science'` instead of `'react-science/ui'`

I removed this change from https://github.com/zakodium-oss/react-science/pull/789 to avoid unnecessary breaking change.
