### ISSUE TITLE
Use styled components instead of `css`

### ISSUE THREAD

**Issue by targos** [zakodium-oss/react-science#806]
This means converting uses from `@emotion/react` and the `css` prop to `@emotion/styled`.

@stropitek do you agree?

**Comment by stropitek** [comment]
Yes I agree. I started migrating some of them already while working on features.

When all instances of a file have been refactored, the `/** @jsxImportSource @emotion/react */` comment can be removed.

**Comment by Sebastien-Ahkrin** [comment]
https://github.com/zakodium-oss/react-science/pull/834#discussion_r1888349554

**Comment by Sebastien-Ahkrin** [comment]
This issue is now fixed by every Refs linked here!
